### ISSUE TITLE
Gnome 3.28.2 does not work

### ISSUE THREAD

**Issue by xzj8b3** [screenfreeze/messagingmenu#42] opened 2018-07-19 23:20 UTC
Gnome 3.28.2 does not work,does not open any menu

**Comment by sinisterstuf** [comment] 2018-08-06 20:11
Can you provide more details please? A screenshot maybe or some logs? What is it you're expecting to happen and what happens instead?

It's unfortunately pretty difficult for me to reproduce because I don't use GNOME any more.

**Comment by xzj8b3** [comment] 2018-09-08 12:54
There is little to provide, in Fedora 28 x64 clicking Icon does not open any ' menu!!!!

**Comment by doogie544** [comment] 2018-10-13 16:34
I can verify that is does not work in 3.28.2.  

Using Ubuntu 18.04 either so it must be extension/gnome related not OS related.

Like the above I cannot provide any more information.  The extension installs with no error from https://extensions.gnome.org/extension/519/messaging-menu/  but clicking the extension icon in the top bar does nothing.

I would be willing to provide error reports, but will need instruction on how to retrieve them- I do not see them in the extensions folder.

**Comment by xzj8b3** [comment] 2018-10-17 12:08
Now I'm on Fedora 29, if you already want to create it for Gnome 3.30 I'll tell you!!!

**Comment by sinisterstuf** [comment] 2019-03-17 21:45
OK, I've finally got access to a computer running GNOME, I am unable to reproduce this issue in GNOME 3.30, so if you're still on 3.28 then I recommend you to upgrade.

I'm closing this issue but if any more issues relating to 3.28.2 arise then feel free to reopen.

**Closed by sinisterstuf** 2019-03-17 21:45 UTC
Labels: bug
